### ISSUE TITLE
URL not appropriately generated after database switch

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7-test-panel#64] opened 2022-08-17 20:50 UTC
<img width="1797" alt="image" src="https://user-images.githubusercontent.com/37256050/185240435-29a9f074-e07c-46f4-9339-2f10679f4677.png">

This happens occasionally after switching databases. See here that the URL is `kufish` while the db is `herb_rbge_2`.

**Comment by maxxxxxdlp** [comment] 2022-08-17 20:51
Duplicate of https://github.com/specify/specify7-test-panel/issues/62

**Closed by maxxxxxdlp** 2022-08-17 20:51 UTC
